"""create simulation runs table

Revision ID: 10768f22a018
Revises: f5641cb14ff8
Create Date: 2026-09-21 02:10:46.199491
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '10768f22a018'
down_revision: Union[str, Sequence[str], None] = 'f5641cb14ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('strategy_id', sa.String(length=100), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('projected_resilience_score', sa.Float(), nullable=True),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_runs_incident_id'), 'simulation_runs', ['incident_id'], unique=False)
    op.create_index(op.f('ix_simulation_runs_strategy_id'), 'simulation_runs', ['strategy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_runs_strategy_id'), table_name='simulation_runs')
    op.drop_index(op.f('ix_simulation_runs_incident_id'), table_name='simulation_runs')
    op.drop_table('simulation_runs')
    # ### end Alembic commands ###
